# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a1579894-59ba-4e3e-9dc0-33eb56c88a60";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8B50-CECE";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/home/avie/HDD" = {
    device = "/dev/disk/by-uuid/3e731123-5ae2-4afb-9a19-0dbc54988177";
    fsType = "ext4";
    options = [
      "users" # Allows any user to mount and unmount
      "nofail" # Prevent system from failing if this drive doesn't mount
    ];
  };
  fileSystems."/home/avie/SSD" = {
    device = "/dev/disk/by-uuid/5c743f27-189e-4920-8265-73064d2fe93e";
    fsType = "ext4";
    options = [
      "users"
      "nofail"
      "exec"
    ];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/59580328-e711-4910-94cf-dd95f6b97e8c";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
